# Stubs for cachecontrol.wrapper (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .adapter import CacheControlAdapter
from .cache import DictCache
from typing import Any, Optional

def CacheControl(sess: Any, cache: Optional[Any] = ..., cache_etags: bool = ..., serializer: Optional[Any] = ..., heuristic: Optional[Any] = ...): ...
