from collections.abc import Generator

from _typeshed import Incomplete

def safe_walk(
    path, allowlist: Incomplete | None = ...
) -> Generator[Incomplete, None, None]: ...
def unsafe_walk(
    path, allowlist: Incomplete | None = ..., username: Incomplete | None = ...
): ...
def joinext(root, ext): ...
def has_ext(path, ext, aliases: bool = ..., ignore: Incomplete | None = ...): ...
def get_ext(path, ignore: Incomplete | None = ..., canonicalize: bool = ...): ...

class Extensions(dict):
    def __missing__(self, key): ...
    def canonicalize(self, ext): ...

extensions: Incomplete
