# Stubs for galaxy.tools.locations.http (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..locations import ToolLocationResolver

class HttpToolResolver(ToolLocationResolver):
    scheme = ...  # type: str
    def __init__(self, **kwds) -> None: ...
    def get_tool_source_path(self, uri_like): ...

class HttpsToolResolver(HttpToolResolver):
    scheme = ...  # type: str
