pull_request_rules:
  - name: Automatic merge on approval and when when GitHub branch protection passes on main
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
    actions:
      merge:
        method: merge
        strict: true
