queue_rules:
  - name: default
    conditions:
      - -draft # not a draft
      - base=main

pull_request_rules:
  - name: Automatic merge on approval and when when GitHub branch protection passes on main
    conditions:
      - "#approved-reviews-by>=1"
      - -draft
      - base=main
    actions:
      queue:
        method: merge
        name: default
        
pull_request_rules:
  - name: Automatic merge for leadership team members when there are no reviewers and the label is "ready"
    conditions:
      - "#review-requested=0"
      - "#changes-requested-reviews-by<1"
      - -draft
      - base=main
      - author=@leadership
      - label=ready
    actions:
      queue:
        method: merge
        name: default
