queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=1"
      - -draft
      - base=main
    merge_conditions:
      - -draft # not a draft
      - base=main
    merge_method: merge

pull_request_rules:
  - name: Automatic merge on approval and when when GitHub branch protection passes
      on main
    conditions: []
    actions:
      queue:
