[tox]
envlist =
  py3{10,11,12,13,14,15}-lint
  py3{10,11,12,13,14,15}-unit
  py3{10,11,12,13,14,15}-bandit
  py3{10,11,12,13,14,15}-mypy
  py314-lintreadme
  py314-shellcheck
  py314-pydocstyle

skip_missing_interpreters = True

[pytest]
addopts=--ignore cwltool/schemas -n logical --dist worksteal -rsfE
testpaths = tests

[gh-actions]
python =
  3.10: py310
  3.11: py311
  3.12: py312
  3.13: py313
  3.14: py314
  3.15: py315

[testenv]
skipsdist =
  py3{10,11,12,13,14,15}-!{unit,mypy,lintreadme} = True

description =
  py3{10,11,12,13,14,15}-unit: Run the unit tests
  py3{10,11,12,13,14,15}-lint: Lint the Python code
  py3{10,11,12,13,14,15}-bandit: Search for common security issues
  py3{10,11,12,13,14,15}-mypy: Check for type safety
  py314-pydocstyle: docstring style checker
  py314-shellcheck: syntax check for shell scripts
  py314-lintreadme: Lint the README.rst→.md conversion

passenv =
  CI
  GITHUB_*
  PROOT_NO_SECCOMP
  APPTAINER_TMPDIR
  SINGULARITY_FAKEROOT
  UDOCKER_*

extras =
  py3{10,11,12,13,14}-unit: deps

deps =
  py3{10,11,12,13,14,15}-{unit,lint,bandit,mypy}: -rrequirements.txt
  py3{10,11,12,13,14,15}-{unit,mypy}: -rtest-requirements.txt
  py3{10,11,12,13,14,15}-lint: -rlint-requirements.txt
  py3{10,11,12,13,14,15}-bandit: bandit
  py3{10,11,12,13,14,15}-mypy: -rmypy-requirements.txt
  py314-pydocstyle: pydocstyle
  py314-pydocstyle: diff-cover
  py314-lintreadme: twine
  py314-lintreadme: build
  py314-lintreadme: readme_renderer[rst]

setenv =
  LC_ALL = C.UTF-8
  HOME = {envtmpdir}

commands_pre =
  py314-lintreadme: make dist

commands =
  py3{10,11,12,13,14,15}-unit: make coverage-report coverage.xml PYTEST_EXTRA="{posargs}"
  py3{10,11,12,13,14,15}-bandit: bandit -r cwltool
  py3{10,11,12,13,14,15}-lint: make flake8 format-check codespell-check
  py3{10,11,12,13,14,15}-mypy: make mypy mypyc PYTEST_EXTRA="{posargs}"
  py314-shellcheck: make shellcheck
  py314-pydocstyle: make diff_pydocstyle_report
  py314-lintreadme: twine check dist/cwltool*

skip_install =
  py3{10,11,12,13,14,15}-{bandit,lint,mypy,shellcheck,pydocstyle,lintreadme}: true

allowlist_externals = make
