# Stubs for galaxy.tools.cwl.cwltool_deps (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

import schema_salad as schema_salad
import shellescape as shellescape
from schema_salad import ref_resolver as ref_resolver

from cwltool import load_tool as load_tool
from cwltool import main as main
from cwltool import pathmapper as pathmapper
from cwltool import process as process
from cwltool import workflow as workflow

main = ...  # type: Any
workflow = ...  # type: Any
process = ...  # type: Any
pathmapper = ...  # type: Any
load_tool = ...  # type: Any
shellescape = ...  # type: Any
schema_salad = ...  # type: Any
ref_resolver = ...  # type: Any
needs_shell_quoting = ...  # type: Any

def ensure_cwltool_available(): ...
