import pickle

from _typeshed import Incomplete

class AliasUnpickler(pickle.Unpickler):
    aliases: Incomplete
    def __init__(self, aliases, *args, **kw) -> None: ...
    def find_class(self, module, name): ...

class AliasPickleModule:
    aliases: Incomplete
    def __init__(self, aliases) -> None: ...
    def dump(self, obj, fileobj, protocol: int = ...): ...
    def dumps(self, obj, protocol: int = ...): ...
    def load(self, fileobj): ...
    def loads(self, string): ...
