from _typeshed import Incomplete

class Bunch:
    def __init__(self, **kwds) -> None: ...
    def dict(self): ...
    def get(self, key, default: Incomplete | None = ...): ...
    def __iter__(self): ...
    def items(self): ...
    def keys(self): ...
    def values(self): ...
    def __bool__(self): ...
    __nonzero__: Incomplete
    def __setitem__(self, k, v) -> None: ...
    def __contains__(self, item): ...
