def check_html(name, file_path: bool = ...): ...
def check_binary(name, file_path: bool = ...): ...
def check_gzip(file_path, check_content: bool = ...): ...
def check_bz2(file_path, check_content: bool = ...): ...
def check_zip(file_path, check_content: bool = ..., files: int = ...): ...
def is_bz2(file_path): ...
def is_gzip(file_path): ...
def is_zip(file_path): ...
def check_image(file_path): ...
