from _typeshed import Incomplete
from galaxy.util import which as which

def redirecting_io(sys=...): ...
def redirect_aware_commmunicate(p, sys=...): ...
def shell(cmds, env: Incomplete | None = ..., **kwds): ...
def shell_process(cmds, env: Incomplete | None = ..., **kwds): ...
def execute(cmds, input: Incomplete | None = ...): ...
def argv_to_str(command_argv, quote: bool = ...): ...
def download_command(url, to=...): ...

class CommandLineException(Exception):
    command: Incomplete
    stdout: Incomplete
    stderr: Incomplete
    returncode: Incomplete
    message: Incomplete
    def __init__(self, command, stdout, stderr, returncode) -> None: ...
