from collections.abc import MutableMapping

from _typeshed import Incomplete

class ExpressionContext(MutableMapping):
    dict: Incomplete
    parent: Incomplete
    def __init__(self, dict, parent: Incomplete | None = ...) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __contains__(self, key): ...
    def __bool__(self): ...
    __nonzero__: Incomplete
