from _typeshed import Incomplete
from collections.abc import MutableMapping

class Facts(MutableMapping):
    __dict__: Incomplete
    def __init__(self, config: Incomplete | None = ..., **kwargs) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value): ...
    def __delitem__(self, key): ...
    def __iter__(self): ...
    def __len__(self): ...

def get_facts(config: Incomplete | None = ..., **kwargs): ...
