from _typeshed import Incomplete

class FileLockException(Exception): ...

class FileLock:
    is_locked: bool
    lockfile: Incomplete
    file_name: Incomplete
    timeout: Incomplete
    delay: Incomplete
    def __init__(self, file_name, timeout: int = ..., delay: float = ...) -> None: ...
    fd: Incomplete
    def acquire(self) -> None: ...
    def release(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, type, value, traceback) -> None: ...
    def __del__(self) -> None: ...
