from _typeshed import Incomplete

class LazyProcess:
    command_and_args: Incomplete
    thread_lock: Incomplete
    allow_process_request: bool
    process: Incomplete
    def __init__(self, command_and_args) -> None: ...
    def start_process(self) -> None: ...
    def shutdown(self) -> None: ...
    @property
    def running(self): ...

class NoOpLazyProcess:
    def start_process(self) -> None: ...
    def shutdown(self) -> None: ...
    @property
    def running(self): ...
