from _typeshed import Incomplete

class RenamedTemporaryFile:
    tmpfile: Incomplete
    final_path: Incomplete
    def __init__(self, final_path, **kwargs) -> None: ...
    def __getattr__(self, attr): ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
