from _typeshed import Incomplete
from galaxy.util.properties import (
    find_config_file as find_config_file,
    load_app_properties as load_app_properties,
)

DESCRIPTION: Incomplete
ACTIONS: Incomplete
ARGUMENTS: Incomplete
DEFAULT_ACTION: Incomplete
ARG_HELP_CONFIG_FILE: str

def main_factory(
    description: Incomplete | None = ...,
    actions: Incomplete | None = ...,
    arguments: Incomplete | None = ...,
    default_action: Incomplete | None = ...,
): ...
def main(argv: Incomplete | None = ...) -> None: ...
def app_properties_from_args(
    args, legacy_config_override: Incomplete | None = ..., app: Incomplete | None = ...
): ...
def config_file_from_args(
    args, legacy_config_override: Incomplete | None = ..., app: Incomplete | None = ...
): ...
def populate_config_args(parser) -> None: ...
def set_log_handler(
    filename: Incomplete | None = ..., stream: Incomplete | None = ...
): ...
