from _typeshed import Incomplete

class CycleError(Exception):
    preds: Incomplete
    def __init__(self, sofar, numpreds, succs) -> None: ...
    def get_partial(self): ...
    def get_pred_counts(self): ...
    def get_succs(self): ...
    def get_elements(self): ...
    def get_pairlist(self): ...
    def get_preds(self): ...
    def pick_a_cycle(self): ...

def topsort(pairlist): ...
def topsort_levels(pairlist): ...
