from _typeshed import Incomplete

def load_with_references(path): ...
def load(path): ...
def template_macro_params(root): ...
def raw_xml_tree(path): ...
def imported_macro_paths(root): ...

class XmlMacroDef:
    elements: Incomplete
    parameters: Incomplete
    def __init__(self, el) -> None: ...
    def macro_tokens(self, expand_el): ...
