# Stubs for prov.tests.test_graphs (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest

class ProvGraphTestCase(unittest.TestCase):
    def test_simple_graph_conversion(self): ...
