# Stubs for prov.tests.utility (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest
from typing import Any, Optional

logger: Any

class DocumentBaseTestCase(unittest.TestCase):
    def do_tests(self, prov_doc, msg: Optional[Any] = ...): ...

class RoundTripTestCase(DocumentBaseTestCase):
    FORMAT: Any = ...
    def do_tests(self, prov_doc, msg: Optional[Any] = ...): ...
    def assertRoundTripEquivalence(self, prov_doc, msg: Optional[Any] = ...): ...
