from typing import Any, Optional

class DeprecationWarning(DeprecationWarning):
    msg: Any = ...
    path: Any = ...
    lineno: Any = ...
    def __init__(self, msg: Any, path: Any, lineno: Any) -> None: ...

def warn(msg: Any, stacklevel: int = ..., function: Optional[Any] = ...) -> None: ...
