# Stubs for rdflib.plugins.parsers.notation3 (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class BadSyntax(SyntaxError):
    lines = ...  # type: Any
    def __init__(self, uri: Any, lines: Any, argstr: Any, i: Any, why: Any): ...
    @property
    def message(self) -> Any: ...
