# Stubs for past.builtins (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from __builtin__ import basestring as basestring, long as long, olddict as dict, oldstr as str
from past.builtins.misc import apply as apply, chr as chr, cmp as cmp, execfile as execfile, intern as intern, raw_input as raw_input, reload as reload, unichr as unichr, unicode as unicode, xrange as xrange
from past.builtins.noniterators import filter as filter, map as map, range as range, reduce as reduce, zip as zip
