# Stubs for prov (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class Error(Exception): ...

def read(source, format: Optional[Any] = ...): ...

# Names in __all__ with no definition:
#   model
