# Stubs for galaxy.tools.linters.inputs (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..lint_util import is_datasource as is_datasource

def lint_inputs(tool_xml, lint_ctx): ...
def lint_repeats(tool_xml, lint_ctx): ...
