# Stubs for cachecontrol.serialize (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.


class Serializer:
    def dumps(self, request, response, body=None): ...

    def loads(self, request, data): ...

    def prepare_response(self, request, cached): ...
