from types import ModuleType
from typing import Any

class Error(EnvironmentError): ...

class ErrorMaker(ModuleType):
    Error: Any = ...
    def __getattr__(self, name: Any): ...
    def checked_call(self, func: Any, *args: Any, **kwargs: Any): ...

error: Any
