from typing import Any

import py._path.common
import py._path.local
import py._path.svnwc
_ApiModule__doc: str

class SvnAuth:
    __init__: Any = ...
    makecmdoptions: Any = ...

class local(py._path.local.PosixPath):
    __init__: Any = ...
    Checkers: Any = ...
    ImportMismatchError: Any = ...
    _ensuredirs: Any = ...
    _ensuresyspath: Any = ...
    _fastjoin: Any = ...
    _getbyspec: Any = ...
    _patternchars: Any = ...
    as_cwd: Any = ...
    atime: Any = ...
    chdir: Any = ...
    check: Any = ...
    chmod: Any = ...
    computehash: Any = ...
    copy: Any = ...
    dirpath: Any = ...
    dump: Any = ...
    ensure: Any = ...
    islink: Any = ...
    join: Any = ...
    listdir: Any = ...
    lstat: Any = ...
    mkdir: Any = ...
    mtime: Any = ...
    new: Any = ...
    open: Any = ...
    pyimport: Any = ...
    pypkgpath: Any = ...
    realpath: Any = ...
    remove: Any = ...
    rename: Any = ...
    samefile: Any = ...
    sep: Any = ...
    setmtime: Any = ...
    size: Any = ...
    stat: Any = ...
    sysexec: Any = ...
    write: Any = ...
    write_binary: Any = ...
    write_text: Any = ...
    __eq__: Any = ...
    __gt__: Any = ...
    __hash__: Any = ...
    __lt__: Any = ...
    __ne__: Any = ...
    @classmethod
    def _gethomedir(self, *args, **kwargs) -> Any: ...
    @classmethod
    def get_temproot(self, *args, **kwargs) -> Any: ...
    @classmethod
    def make_numbered_dir(self, *args, **kwargs) -> Any: ...
    @classmethod
    def mkdtemp(self, *args, **kwargs) -> Any: ...
    @classmethod
    def sysfind(self, *args, **kwargs) -> Any: ...

class svnurl(py._path.svnwc.SvnPathBase):
    _cmdexec: Any = ...
    _encodedurl: Any = ...
    _listdir_nameinfo: Any = ...
    _lsnorevcache: Any = ...
    _lsrevcache: Any = ...
    _norev_delentry: Any = ...
    _popen: Any = ...
    _propget: Any = ...
    _proplist: Any = ...
    _svncmdexecauth: Any = ...
    _svnpopenauth: Any = ...
    _svnwithrev: Any = ...
    _svnwrite: Any = ...
    copy: Any = ...
    dirpath: Any = ...
    ensure: Any = ...
    export: Any = ...
    info: Any = ...
    listdir: Any = ...
    log: Any = ...
    mkdir: Any = ...
    open: Any = ...
    remove: Any = ...
    rename: Any = ...
    def __init__(self, *args, **kwargs) -> None: ...

class svnwc(py._path.common.PathBase):
    Checkers: Any = ...
    _authsvn: Any = ...
    _ensuredirs: Any = ...
    _escape: Any = ...
    _getbyspec: Any = ...
    _geturl: Any = ...
    _makeauthoptions: Any = ...
    _rex_commit: Any = ...
    _svn: Any = ...
    add: Any = ...
    blame: Any = ...
    checkout: Any = ...
    cleanup: Any = ...
    commit: Any = ...
    copy: Any = ...
    diff: Any = ...
    dirpath: Any = ...
    dump: Any = ...
    ensure: Any = ...
    info: Any = ...
    join: Any = ...
    listdir: Any = ...
    lock: Any = ...
    log: Any = ...
    mkdir: Any = ...
    mtime: Any = ...
    new: Any = ...
    open: Any = ...
    propdel: Any = ...
    propget: Any = ...
    proplist: Any = ...
    propset: Any = ...
    remove: Any = ...
    rename: Any = ...
    revert: Any = ...
    sep: Any = ...
    size: Any = ...
    status: Any = ...
    svnurl: Any = ...
    switch: Any = ...
    unlock: Any = ...
    update: Any = ...
    write: Any = ...
    __eq__: Any = ...
    __hash__: Any = ...
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def rev(self) -> Any: ...
    @property
    def strpath(self) -> Any: ...
    @property
    def url(self) -> Any: ...
