# Stubs for networkx.algorithms.hierarchy (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def flow_hierarchy(G, weight: Optional[Any] = ...): ...
