# Stubs for networkx.algorithms.mis (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def maximal_independent_set(G, nodes: Optional[Any] = ...): ...
