# Stubs for networkx.algorithms.wiener (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def wiener_index(G, weight: Optional[Any] = ...): ...
