# Stubs for networkx.algorithms.flow.boykovkolmogorov (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def boykov_kolmogorov(
    G,
    s,
    t,
    capacity: str = ...,
    residual: Optional[Any] = ...,
    value_only: bool = ...,
    cutoff: Optional[Any] = ...,
): ...
