# Stubs for galaxy.tools.loader (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

from galaxy.util.xml_macros import imported_macro_paths as imported_macro_paths
from galaxy.util.xml_macros import raw_tool_xml_tree as raw_tool_xml_tree
from galaxy.util.xml_macros import template_macro_params as template_macro_params

load_tool = ...  # type: Any
