language: python
python: 2.7
os:
  - linux
env:
  - TOX_ENV=py27-lint
  - TOX_ENV=py27-unit
  - TOX_ENV=py34-mypy
#  - TOX_ENV=py34-lint
#  - TOX_ENV=py33-lint
#  - TOX_ENV=py34-unit
#  - TOX_ENV=py33-unit

install:
  - pip install tox

script: tox -e $TOX_ENV

notifications:
  email: false
