# Stubs for networkx.algorithms.centrality.current_flow_betweenness (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

from networkx.algorithms.centrality.flow_matrix import *

def approximate_current_flow_betweenness_centrality(
    G,
    normalized: bool = ...,
    weight: Optional[Any] = ...,
    dtype: Any = ...,
    solver: str = ...,
    epsilon: float = ...,
    kmax: int = ...,
): ...
def current_flow_betweenness_centrality(
    G,
    normalized: bool = ...,
    weight: Optional[Any] = ...,
    dtype: Any = ...,
    solver: str = ...,
): ...
def edge_current_flow_betweenness_centrality(
    G,
    normalized: bool = ...,
    weight: Optional[Any] = ...,
    dtype: Any = ...,
    solver: str = ...,
): ...
