# Stubs for prov.serializers.provxml (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from prov.constants import *
import prov.identifier
from typing import Any, Optional

__email__: str
logger: Any
FULL_NAMES_MAP: Any
FULL_PROV_RECORD_IDS_MAP: Any
XML_XSD_URI: str

class ProvXMLException(prov.Error): ...

class ProvXMLSerializer(prov.serializers.Serializer):
    def serialize(self, stream, force_types: bool = ..., **kwargs): ...
    def serialize_bundle(self, bundle, element: Optional[Any] = ..., force_types: bool = ...): ...
    def deserialize(self, stream, **kwargs): ...
    def deserialize_subtree(self, xml_doc, bundle): ...

def xml_qname_to_QualifiedName(element, qname_str): ...
