# Stubs for networkx.algorithms.bipartite.redundancy (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def node_redundancy(G, nodes: Optional[Any] = ...): ...
