import py
from subprocess import PIPE as PIPE, Popen as Popen
from typing import Any

def cmdexec(cmd: Any): ...

class ExecutionFailed(py.error.Error):
    status: Any = ...
    systemstatus: Any = ...
    cmd: Any = ...
    err: Any = ...
    out: Any = ...
    def __init__(self, status: Any, systemstatus: Any, cmd: Any, out: Any, err: Any) -> None: ...
