from typing import Any, Optional

def get_unbuffered_io(fd: Any, filename: Any): ...

class ForkedFunc:
    EXITSTATUS_EXCEPTION: int = ...
    fun: Any = ...
    args: Any = ...
    kwargs: Any = ...
    tempdir: Any = ...
    RETVAL: Any = ...
    STDOUT: Any = ...
    STDERR: Any = ...
    pid: Any = ...
    def __init__(self, fun: Any, args: Optional[Any] = ..., kwargs: Optional[Any] = ..., nice_level: int = ..., child_on_start: Optional[Any] = ..., child_on_exit: Optional[Any] = ...) -> None: ...
    def waitfinish(self, waiter: Any = ...): ...
    def __del__(self) -> None: ...

class Result:
    exitstatus: Any = ...
    signal: Any = ...
    retval: Any = ...
    out: Any = ...
    err: Any = ...
    def __init__(self, exitstatus: Any, signal: Any, retval: Any, stdout: Any, stderr: Any) -> None: ...
