# Stubs for networkx.algorithms.assortativity.neighbor_degree (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def average_neighbor_degree(
    G,
    source: str = ...,
    target: str = ...,
    nodes: Optional[Any] = ...,
    weight: Optional[Any] = ...,
): ...
