sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
os:
  - linux
jobs:
  include:
    - stage: release-test
      script: RELEASE_SKIP=head PYVER= ./release-test.sh
script: tox
install:
  - pip install tox-travis
notifications:
  email: false
