from typing import Any

builtin_repr = repr
reprlib: Any

class SafeRepr(reprlib.Repr):
    def repr(self, x: Any): ...
    def repr_unicode(self, x: Any, level: Any): ...
    def repr_instance(self, x: Any, level: Any): ...

def saferepr(obj: Any, maxsize: int = ...): ...
