name: CI tests

on:
  push:
  pull_request:

jobs:

  tox:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - py-semver: 3.6
            py-toxver: py36
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.py-semver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-semver }}

      - name: Install Tox and any other packages
        run: pip install tox

      - name: Linting for ${{ matrix.py-semver }}
        run: tox -e ${{ matrix.py-toxver }}-lint
