name: CI tests

on:
  push:
  pull_request:

jobs:

  tox:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        py-semver: [3.6]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.py-semver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-semver }}

      - name: Install Tox and any other packages
        run: |
          python -m pip install --upgrade pip
          pip install -rrequirements.txt -rtest-requirements.txt tox tox-gh-actions

      - name: Test with tox
        run: tox
