name: CI tests

on:
  push:
  pull_request:

jobs:

  tox:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        py-semver: [3.6]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v5
        with:
          singularity-version: 3.6.4

      - name: Set up Python ${{ matrix.py-semver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-semver }}

      - name: Give the test runner user a name to make provenance happy.
        run: sudo usermod -c 'CI Runner' $(whoami)

      - name: Cache installed python modules
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt', 'test-requirements.txt') }}

      - name: Install Tox and any other packages
        run: |
          python -m pip install --upgrade pip
          pip install -rrequirements.txt -rtest-requirements.txt tox tox-gh-actions

      - name: MyPy cache
        uses: actions/cache@v2
        with:
          path: .mypy_cache/${{ matrix.py-semver }}
          key: mypy-${{ matrix.py-semver }}

      - name: Test with tox
        run: tox
